name: Deploy Closing Costs Lambda Function
#run-name: Dev Deploy ${{ matrix.lambdaFunction }} Lambda Function
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      lambdaFunction:
        type: string
        description: Lambda
        required: true

jobs:
  generate_matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-22.04
    steps:
      # - name: setting branch names as environment variables
      #   run: |
      #     echo "base_branch=${{github.ref_name}}" 
      #     echo "compare_branch=${{github.ref}}" 
      #     echo "${{ github.event.before}}" 
      - uses: actions/checkout@v3
      # - name: Get merged branch name
        # run: |
          # MERGED_BRANCH=$(git log -1 --pretty=%D | grep -oP 'origin/\K[^,]+')
          # echo "Merged branch name: $MERGED_BRANCH"
          # PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].number')
          # PR_BRANCH=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.head.ref')
          # echo "$PR_NUMBER"
          # echo "Merged PR branch name: $PR_BRANCH"
      - name: final
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].number')
          PR_BRANCH=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.head.ref')
          echo "compare_branch=$PR_BRANCH" 
          echo "base_branch=${{github.ref_name}}"  


